version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stock_computing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m uvicorn stock_computing_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: "db"
