apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: stock-computing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: stock-computing-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: stock-computing-app
    spec:
      containers:
      - name: postgres
        image: postgres:13.3-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
