apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: stock-computing-app
spec:
  type: LoadBalancer
  clusterIP: 10.0.0.1
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    matchLabels:
      name: postgres-pod
      app: stock-computing-app
