name: Publish-PyPI-Distributions
run-name: ${{ github.actor }} is publishing project to PyPI using GitHub Actions 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pypi:
    if: github.event.commits[0].author.name != 'GitHubActions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Configure Git
        run: |
          git config user.email "<>"
          git config user.name "GitHubActions"
  
      - name: Bump version number
        run: |
          poetry version prerelease
          git add pyproject.toml
          git commit -m "Bump version to $(poetry version | cut -d ' ' -f 2)"
  
      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: dist/
          verify_metadata: true
          skip_existing: true
          verbose: true
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          body: 'Release v${{ env.RELEASE_VERSION }}'
          draft: false
          prerelease: true
