name: Publish-PyPI-Distributions
run-name: ${{ github.actor }} is publishing project to PyPI using GitHub Actions 🚀

on:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: dist/
          verify_metadata: true
          skip_existing: true
          verbose: true

      - name: Bump version and push changes
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          automatic_release_tag: true
          draft: false
          prerelease: true
          title: Release v${{ env.RELEASE_TAG }}
          files: dist/*
